In [98]:
#descriptions:
# Due to the nature of instagram being picture picture/video first, unlike facebook, x, or threads which people can share their thoughts as a written post, it's difficult to yield relevant informations on instagram.
# rows with 'replysource' being not null is an indication that the row is a reply/comment of a source post, thus at a glance their data seem to don't correlate much but they actually does,
# though the weakness is

In [120]:
import pandas as pd
import numpy as np

#facebook
pd.set_option('display.max_colwidth', None)
data = pd.read_csv('scraping/out/facebook_vaccine_2024_2026.classified.csv', na_values=['NaN', -1])
data = data.dropna(subset=['postdate'])
data['postdate'] = pd.to_datetime(data['postdate'])
data = data.drop_duplicates(subset=['tweet'])
data = data[(data['is_relevant'] == True) | (data["replysource"].notna())]
data = data[data['is_indonesian'] == True]
data = data.rename(columns={'retweets': 'shares'})
data = data.drop(columns=['index', 'views', 'veto_reason', 'has_topic_keyword', 'borderline', 'relevance_score', 'is_indonesian', 'is_relevant'])
# data = data[data['replysource'] == 'https://web.facebook.com/cintaofficial1212/posts/pfbid0eGCKu3qjJ9TBhE9d7NXSAZxUH5bTn1KeTcDjsgACNFYBAqyFTKzvhzyznGddGCJ4l']
# data[data.duplicated(subset=['tweet'], keep=False)]
# data = data[data['retweets'] != 0]
# data = data[data['replysource'].notna()]
print('facebook data count: ', len(data))
data_fb = data
data.head(1)

facebook data count:  1106

,account,postdate,tweet,link,comments,shares,likes,replysource
3,Bao Chenx,2025-08-29 14:20:00+00:00,"Sumpah ,udah puluhan anak yg gua bantu nanganin campak.. Dulu sebelum gua tau penyembuhan alami aja, gua kasih herbal China namanya ""MAPO"" pada sembuh..Apalagi sekarang, makin gua anggap cetek lah.… Lihat selengkapnya",https://web.facebook.com/photo/?fbid=757232593738471&set=a.101256392669431,196,61,477,NaN

In [121]:
#instagram
data = pd.read_csv('scraping/out/instagram_vaccine_2024_2026.classified.csv', na_values=['NaN', -1])
data_old = pd.read_csv('old_result/instagram_vaccine.csv', na_values=['NaN', -1])
data = pd.concat([data, data_old], axis=0, ignore_index = True)
data = data.dropna(subset=['postdate'])
# data['reposts'] = np.nan
# data = data.rename(columns={'retweets': 'reposts'})
data = data[(data['is_relevant'] == True)]
data = data[data['is_indonesian'] == True]
data['postdate'] = pd.to_datetime(data['postdate'])
data = data.drop_duplicates(subset=['tweet'])
data = data.drop_duplicates(subset=['link'])
data = data.dropna(subset=['postdate'])
data = data.drop(columns=['index', 'retweets', 'views', 'replysource', 'veto_reason', 'has_topic_keyword', 'borderline', 'relevance_score', 'is_indonesian', 'is_relevant'])
# data = data[data['is_relevant'] == True]
# data = data[data['replysource'].notna()]
print('instagram data count: ', len(data))
data_ig = data
data.head(1)

instagram data count:  7

,account,postdate,tweet,link,comments,likes
85,klinikutamatanaya,2026-05-29 08:11:58+00:00,"[BARU] Yuk vaksin di Klinik Utama Tanaya! 🏥💉💉 Ada beberapa layanan vaksinasi di Klinik Utama Tanaya Bandung lho ---------- Layanan Vaksin Influenza (Flu) Mulai dari Rp 345,000 ---------- Jenis-jenis vaksin influenza kami: - Influenza - Fluarix Tetra - Influenza - Vaxigrip Tetra - Influenza - Vaxigrip Trivalen . . Layanan Vaksin HPV Mulai dari Rp 1,395,000 -------------- Jenis-jenis Vaksin HPV kami - HPV 4 - Gardasil 4 - HPV 9 - Gardasil 9 --------------- Vaksin Campak, Rubella, Gondong: - MMR - MR - MMRV -------------- Jenis-jenis vaksin Pneumonia kami: - PCV 13 - PCV 15 - PCV 20 --------------- *Harga vaksin sudah termasuk jasa suntik dokter umum & administrasi *Tersedia layanan vaksinasi oleh dokter spesialis (harga berbeda) --------------- UNTUK RESERVASI: SILAHKAN LANGSUNG MENGHUBUNGI NOMOR WA YANG TERTERA DI PROFIL KAMI Alamat kami: Jl. Sulanjana No. 11A Bandung #vaksininfluenza #vaksin #vaksinhpv #vaksinbandung #vaksinpneumonia",https://www.instagram.com/p/DY6lgzTpiKx/,0,7

In [122]:
#threads
data = pd.read_csv('scraping/out/threads_vaccine_2024_2026.classified.csv', na_values=['NaN', -1])
data_old = pd.read_csv('old_result/threads_vaccine.csv', na_values=['NaN', -1])
data = pd.concat([data, data_old], axis=0, ignore_index = True)
data = data.dropna(subset=['postdate'])
data = data[(data['is_relevant'] == True) | (data["replysource"].notna())]
data = data[data['is_indonesian'] == True]
data['postdate'] = pd.to_datetime(data['postdate'])
data = data.drop_duplicates(subset=['tweet'])
# data = data.drop_duplicates(subset=['link'])
data = data.dropna(subset=['postdate'])
data['tweet'] = data.apply(lambda row: row['tweet'].removeprefix(row['account']), axis=1)
data['tweet'] = data.apply(lambda row: row['tweet'].removeprefix('Verified '), axis=1)
data = data.drop(columns=['index', 'veto_reason', 'has_topic_keyword', 'borderline', 'relevance_score', 'is_indonesian', 'is_relevant'])
# data = data[data['retweets'] != 0]
# data = data[data['replysource'].notna()]
print('threads data count: ', len(data))
data_th = data
data.head(1)

threads data count:  8170

,account,postdate,tweet,link,topic_tag,comments,retweets,likes,shares,replysource
0,sofiahafh,2026-01-15 11:03:25+00:00,"Habis imunisasi campak, malah kena campak. Asw Mau stop imunisasi aja rasanya kek gini Translate 1/2 Habis imunisasi campak, malah kena campak. Asw Mau stop imunisasi aja rasanya kek gini",https://www.threads.com/@sofiahafh/post/DTh2nzpkqJa,NaN,121,1,15,6,NaN

In [123]:
#X
data = pd.read_csv('scraping/out/x_vaccine_2024_2026.classified.csv', na_values=['NaN', -1])
data_old = pd.read_csv('old_result/x_vaccine.csv', na_values=['NaN', -1])
data = pd.concat([data, data_old], axis=0, ignore_index = True)
data = data.dropna(subset=['postdate'])
data = data[(data['is_relevant'] == True)]
data = data[data['is_indonesian'] == True]
data['postdate'] = pd.to_datetime(data['postdate'])
data = data.drop_duplicates(subset=['tweet'])
data = data.drop_duplicates(subset=['link'])
data = data.dropna(subset=['postdate'])
data = data[data['index'] != 5]
data = data.drop(columns=['index', 'veto_reason', 'has_topic_keyword', 'borderline', 'relevance_score', 'is_indonesian', 'is_relevant'])
# data = data[data['retweets'] != 0]
# data = data[data['replysource'].notna()]
print('X data count: ', len(data))
data_x = data
data.head(1)

X data count:  1188

,account,postdate,tweet,link,comments,retweets,likes,views,replysource
18,syaikhkhalid,2024-06-11 23:24:02+00:00,Lalu buat apa komnas kipi dibuat kalau gak ada efek samping vaksin? kayak vaksin ini cairan dari surga saja. Berpikirlah lebih cerdas jangan bersikap khianat seperti itu,https://x.com/syaikhkhalid/status/1800670356224737530,0,0,8,417.0,NaN

In [125]:
data_fb['platform'] = 'facebook'
data_ig['platform'] = 'instagram'
data_th['platform'] = 'threads'
data_x['platform'] = 'x'
merged_data = pd.concat([data_fb, data_ig, data_th, data_x], axis=0, ignore_index=True)
merged_data
merged_data.to_csv('cleaned_data.csv', index=False)